import { i as OpenClawConfig } from "../types.openclaw-20mzwaMw.js";
import { n as normalizeChatType } from "../chat-type-B6XXSSnm.js";
import { n as normalizeAccountId, r as normalizeOptionalAccountId, t as DEFAULT_ACCOUNT_ID } from "../account-id-Dh6XMgGH.js";
import { l as normalizeE164, p as resolveUserPath, u as pathExists } from "../utils-CRegZsWE.js";
import { t as createAccountActionGate } from "../account-action-gate-D0GCq_WL.js";
import { a as listCombinedAccountIds, c as resolveMergedAccountConfig, i as hasConfiguredAccountValue, n as describeAccountSnapshot, o as mergeAccountConfig, s as resolveListedDefaultAccountId, t as createAccountListHelpers } from "../account-helpers-D8q44hLZ.js";
import { n as resolveNormalizedAccountEntry, t as resolveAccountEntry } from "../account-lookup-AwHuXBzh.js";
import { t as listConfiguredAccountIds } from "../account-configured-ids-4opiay54.js";
import { t as resolveAccountWithDefaultFallback } from "../account-core-BELXST_5.js";
export { DEFAULT_ACCOUNT_ID, type OpenClawConfig, createAccountActionGate, createAccountListHelpers, describeAccountSnapshot, hasConfiguredAccountValue, listCombinedAccountIds, listConfiguredAccountIds, mergeAccountConfig, normalizeAccountId, normalizeChatType, normalizeE164, normalizeOptionalAccountId, pathExists, resolveAccountEntry, resolveAccountWithDefaultFallback, resolveListedDefaultAccountId, resolveMergedAccountConfig, resolveNormalizedAccountEntry, resolveUserPath };