import { i as OpenClawConfig } from "../types.openclaw-20mzwaMw.js";
import { r as ChannelConfigUiHint } from "../types.config-D1pSqbn8.js";
import { $n as PluginRuntime } from "../types-BJ3mu3UU.js";
import { t as ChannelPlugin } from "../types.plugin-By-iwHAc.js";
import { L as PluginCommandContext, g as OpenClawPluginApi } from "../plugin-entry-itxMoclV.js";
import { r as buildChannelConfigSchema } from "../config-schema-jXAeMqcd.js";
import { t as clearAccountEntryFields } from "../config-helpers-Ch_sthbJ.js";
import { r as parseOptionalDelimitedEntries } from "../helpers-CweSEiet.js";
import { c as tryReadSecretFileSync } from "../secret-file-DbiHRw7A.js";
import { a as buildThreadAwareOutboundSessionRoute, c as defineChannelPluginEntry, f as recoverCurrentThreadSessionId, i as buildChannelOutboundSessionRoute, l as defineSetupPluginEntry, m as stripTargetKindPrefix, p as stripChannelTargetPrefix, s as createChatChannelPlugin, t as ChannelOutboundSessionRouteParams } from "../core-CUaW3XyL.js";
import { t as createChannelPluginBase } from "../channel-core-C7etOWan.js";
export { type ChannelConfigUiHint, type ChannelOutboundSessionRouteParams, type ChannelPlugin, type OpenClawConfig, type OpenClawPluginApi, type PluginCommandContext, type PluginRuntime, buildChannelConfigSchema, buildChannelOutboundSessionRoute, buildThreadAwareOutboundSessionRoute, clearAccountEntryFields, createChannelPluginBase, createChatChannelPlugin, defineChannelPluginEntry, defineSetupPluginEntry, parseOptionalDelimitedEntries, recoverCurrentThreadSessionId, stripChannelTargetPrefix, stripTargetKindPrefix, tryReadSecretFileSync };