import { $n as PluginRuntime, C as OpenClawPluginApi } from "../types-BJ3mu3UU.js";
import { n as normalizeAccountId, t as DEFAULT_ACCOUNT_ID } from "../account-id-Dh6XMgGH.js";
import { y as ChannelMessageActionContext } from "../types.core-CZRuyur5.js";
import { t as ChannelPlugin } from "../types.plugin-By-iwHAc.js";
import { r as emptyPluginConfigSchema } from "../config-schema-BlT2EOxP.js";
import { r as buildChannelConfigSchema } from "../config-schema-jXAeMqcd.js";
import { s as migrateBaseNameToDefaultAccount, t as applyAccountNameToChannelSection } from "../setup-helpers-CEEMHs5p.js";
import { n as deleteAccountFromConfigSection, r as setAccountEnabledInConfigSection, t as clearAccountEntryFields } from "../config-helpers-Ch_sthbJ.js";
import { n as formatPairingApproveHint } from "../helpers-CweSEiet.js";
import { t as PAIRING_APPROVED_MESSAGE } from "../pairing-message-CFjlYpMw.js";
import { t as getChatChannelMeta } from "../channel-plugin-common-DlfCDld6.js";
export { type ChannelMessageActionContext, type ChannelPlugin, DEFAULT_ACCOUNT_ID, type OpenClawPluginApi, PAIRING_APPROVED_MESSAGE, type PluginRuntime, applyAccountNameToChannelSection, buildChannelConfigSchema, clearAccountEntryFields, deleteAccountFromConfigSection, emptyPluginConfigSchema, formatPairingApproveHint, getChatChannelMeta, migrateBaseNameToDefaultAccount, normalizeAccountId, setAccountEnabledInConfigSection };