import { i as OpenClawConfig } from "../types.openclaw-20mzwaMw.js";
import { a as ImageGenerationProviderPlugin } from "../types-BJ3mu3UU.js";
import { t as FallbackAttempt } from "../model-fallback.types-BQfVfFgq.js";
import { s as AuthProfileStore } from "../types-BLLmx7NZ.js";
import { n as createSubsystemLogger } from "../subsystem-CfQVin8T.js";
import { n as getProviderEnvVars } from "../provider-env-vars-CNa7yLK3.js";
import { _ as ImageGenerationSourceImage, d as ImageGenerationProviderConfiguredContext, f as ImageGenerationProviderOptions, g as ImageGenerationResult, h as ImageGenerationResolution, l as ImageGenerationProvider, m as ImageGenerationRequest, t as GeneratedImageAsset } from "../types-CNRYqs2u2.js";
import { u as normalizeGooglePreviewModelId } from "../provider-model-shared-JMZ9A2m4.js";
import { n as resolveAgentModelPrimaryValue, t as resolveAgentModelFallbackValues } from "../model-input-WydzjhuC.js";
import { n as resolveApiKeyForProvider, r as parseImageGenerationModelRef, t as OPENAI_DEFAULT_IMAGE_MODEL } from "../image-generation-core-CA9I4KYC.js";
import { n as isFailoverError, t as describeFailoverError } from "../failover-error-DdKJLPBP.js";
import { p as throwCapabilityGenerationFailure, r as buildNoCapabilityModelConfiguredMessage, s as resolveCapabilityModelCandidates } from "../runtime-shared-Ct8Fk5E2.js";
import { n as listImageGenerationProviders, t as getImageGenerationProvider } from "../provider-registry-1e1DBzNf.js";
export { type AuthProfileStore, type FallbackAttempt, type GeneratedImageAsset, type ImageGenerationProvider, type ImageGenerationProviderConfiguredContext, type ImageGenerationProviderOptions, type ImageGenerationProviderPlugin, type ImageGenerationRequest, type ImageGenerationResolution, type ImageGenerationResult, type ImageGenerationSourceImage, OPENAI_DEFAULT_IMAGE_MODEL, type OpenClawConfig, buildNoCapabilityModelConfiguredMessage, createSubsystemLogger, describeFailoverError, getImageGenerationProvider, getProviderEnvVars, isFailoverError, listImageGenerationProviders, normalizeGooglePreviewModelId as normalizeGoogleModelId, parseImageGenerationModelRef, resolveAgentModelFallbackValues, resolveAgentModelPrimaryValue, resolveApiKeyForProvider, resolveCapabilityModelCandidates, throwCapabilityGenerationFailure };