import { n as resolvePreferredOpenClawTmpDir } from "../tmp-openclaw-dir-DOKojISm.js";
import { i as withTempWorkspaceSync, n as tempWorkspaceSync, r as withTempWorkspace, t as tempWorkspace } from "../private-temp-workspace-MCwLg_M9.js";
import { n as isToolAllowed } from "../tool-policy-COLnylCG.js";
import { n as resolveSandboxRuntimeStatus } from "../runtime-status-BHJyN0mT.js";
import { t as sanitizeEnvVars } from "../sanitize-env-vars-Bsu9AQgI.js";
import { C as resolveWritableRenameTargetsForBridge, S as resolveWritableRenameTargets, _ as uploadDirectoryToSshTarget, a as getSandboxBackendManager, c as buildExecRemoteCommand, d as buildValidatedExecRemoteCommand, f as createSshSandboxSessionFromConfigText, g as shellEscape, h as runSshSandboxCommand, i as getSandboxBackendFactory, l as buildRemoteCommand, m as disposeSshSandboxSession, o as registerSandboxBackend, p as createSshSandboxSessionFromSettings, s as requireSandboxBackendFactory, u as buildSshSandboxArgv, v as createRemoteShellSandboxFsBridge, x as createWritableRenameTargetResolver } from "../browser-bridges-B8hspklh.js";
import { t as runPluginCommandWithTimeout } from "../run-command-ElF-GKk7.js";
import "../sandbox-Dyl40Uc9.js";
export { buildExecRemoteCommand, buildRemoteCommand, buildSshSandboxArgv, buildValidatedExecRemoteCommand, createRemoteShellSandboxFsBridge, createSshSandboxSessionFromConfigText, createSshSandboxSessionFromSettings, createWritableRenameTargetResolver, disposeSshSandboxSession, getSandboxBackendFactory, getSandboxBackendManager, isToolAllowed, registerSandboxBackend, requireSandboxBackendFactory, resolvePreferredOpenClawTmpDir, resolveSandboxRuntimeStatus, resolveWritableRenameTargets, resolveWritableRenameTargetsForBridge, runPluginCommandWithTimeout, runSshSandboxCommand, sanitizeEnvVars, shellEscape, tempWorkspace, tempWorkspaceSync, uploadDirectoryToSshTarget, withTempWorkspace, withTempWorkspaceSync };
