import { i as OpenClawConfig } from "../../types.openclaw-20mzwaMw.js";
import { rt as GoogleChatConfig, tt as GoogleChatAccountConfig } from "../../types.channels-BwiRzD0c.js";
import { n as isDangerousNameMatchingEnabled } from "../../dangerous-name-matching-B_Cqmdql.js";
import { $n as PluginRuntime } from "../../types-BJ3mu3UU.js";
import { D as readStringParam, S as readNumberParam, d as createActionGate, g as jsonResult, w as readReactionParams } from "../../common-VVxOIn5D.js";
import { t as DEFAULT_ACCOUNT_ID } from "../../account-id-Dh6XMgGH.js";
import { d as readRemoteMediaBuffer } from "../../fetch-BMJMSs8r.js";
import { P as ChannelStatusIssue, v as ChannelMessageActionAdapter } from "../../types.core-CZRuyur5.js";
import { t as ChannelMessageActionName } from "../../types.public-BLanKCB0.js";
import { p as resolveInboundMentionDecision } from "../../mention-gating-D6dFDlTf.js";
import { i as createChannelReplyPipeline } from "../../reply-pipeline-BVvH_NKt.js";
import { r as buildChannelConfigSchema } from "../../config-schema-jXAeMqcd.js";
import { a as fetchWithSsrFGuard } from "../../fetch-guard-BKvfwdRa.js";
import { D as resolveChannelMediaMaxBytes } from "../../media-runtime-CjY6o7UI.js";
import { a as warnMissingProviderGroupPolicyFallbackOnce, n as resolveAllowlistProviderRuntimeGroupPolicy, r as resolveDefaultGroupPolicy, t as GROUP_POLICY_BLOCKED_LABEL } from "../../runtime-group-policy-DEj6LNUz.js";
import { i as WebhookInFlightLimiter, l as readJsonWebhookBodyOrReject, s as createWebhookInFlightLimiter } from "../../webhook-request-guards-DAKACTVp.js";
import { o as registerWebhookTargetWithPluginRoute, p as withResolvedWebhookRequestPipeline, u as resolveWebhookTargetWithAuthOrReject } from "../../webhook-targets-BgUkQbFe.js";
import { n as resolveWebhookPath } from "../../webhook-path-DJByLAD7.js";
import { t as PAIRING_APPROVED_MESSAGE } from "../../pairing-message-CFjlYpMw.js";
import { n as GoogleChatConfigSchema } from "../../bundled-channel-config-schema-CI6KTArZ.js";
import { i as createAccountStatusSink, s as runPassiveAccountLifecycle } from "../../channel-lifecycle.core-BvcgdZUx.js";
import { l as loadOutboundMediaFromUrl } from "../../outbound-media-DGjHHo1-.js";
import { r as createChannelPairingController } from "../../channel-pairing-Dd94ZNLz.js";
import { t as chunkTextForOutbound } from "../../text-chunking-CuFAtrpW.js";
import { m as missingTargetError } from "../../channel-feedback-CK92csJM.js";
import { t as extractToolSend } from "../../tool-send-_qCqjD8-.js";
import { r as resolveInboundRouteEnvelopeBuilderWithRuntime } from "../../inbound-envelope-CyqvCT28.js";
import { t as setGoogleChatRuntime } from "../../runtime-api-D0rnv3VM.js";
export { type ChannelMessageActionAdapter, type ChannelMessageActionName, type ChannelStatusIssue, DEFAULT_ACCOUNT_ID, GROUP_POLICY_BLOCKED_LABEL, type GoogleChatAccountConfig, type GoogleChatConfig, GoogleChatConfigSchema, type OpenClawConfig, PAIRING_APPROVED_MESSAGE, type PluginRuntime, type WebhookInFlightLimiter, buildChannelConfigSchema, chunkTextForOutbound, createAccountStatusSink, createActionGate, createChannelReplyPipeline as createChannelMessageReplyPipeline, createChannelPairingController, createWebhookInFlightLimiter, extractToolSend, fetchWithSsrFGuard, isDangerousNameMatchingEnabled, jsonResult, loadOutboundMediaFromUrl, missingTargetError, readJsonWebhookBodyOrReject, readNumberParam, readReactionParams, readRemoteMediaBuffer, readStringParam, registerWebhookTargetWithPluginRoute, resolveAllowlistProviderRuntimeGroupPolicy, resolveChannelMediaMaxBytes, resolveDefaultGroupPolicy, resolveInboundMentionDecision, resolveInboundRouteEnvelopeBuilderWithRuntime, resolveWebhookPath, resolveWebhookTargetWithAuthOrReject, runPassiveAccountLifecycle, setGoogleChatRuntime, warnMissingProviderGroupPolicyFallbackOnce, withResolvedWebhookRequestPipeline };