import { i as OpenClawConfig } from "../../types.openclaw-20mzwaMw.js";
import { S as MarkdownTableMode, _ as GroupPolicy } from "../../types.base-D238NWJT.js";
import { o as GroupToolPolicyConfig } from "../../types.tools-DZk2axJU.js";
import { G as MSTeamsReplyStyle, H as MSTeamsChannelConfig, U as MSTeamsCloudName, W as MSTeamsConfig, q as MSTeamsTeamConfig } from "../../types.channels-BwiRzD0c.js";
import { n as isDangerousNameMatchingEnabled } from "../../dangerous-name-matching-B_Cqmdql.js";
import { o as SsrFPolicy } from "../../ssrf-skjEI_i5.js";
import { $n as PluginRuntime } from "../../types-BJ3mu3UU.js";
import { n as RuntimeEnv } from "../../runtime-Bxifh4bY.js";
import { t as DEFAULT_ACCOUNT_ID } from "../../account-id-Dh6XMgGH.js";
import { i as getFileExtension, n as detectMime, r as extensionForMime } from "../../mime-B6baDqNM.js";
import { n as ChannelOutboundAdapter } from "../../outbound.types-DMuJZiav.js";
import { m as ChannelGroupContext, t as BaseProbeResult, u as ChannelDirectoryEntry } from "../../types.core-CZRuyur5.js";
import { O as buildMediaPayload, r as ReplyPayload } from "../../reply-payload-wb3lKGla.js";
import { t as ChannelPlugin } from "../../types.plugin-By-iwHAc.js";
import { t as ChannelMessageActionName } from "../../types.public-BLanKCB0.js";
import { l as extractOriginalFilename } from "../../store-D6pQmvkB.js";
import { a as resolveToolsBySender } from "../../group-policy-_fWwzN13.js";
import { i as createChannelReplyPipeline } from "../../reply-pipeline-BVvH_NKt.js";
import { c as resolveAllowlistMatchSimple, t as AllowlistMatch } from "../../allowlist-match-Bmdv70ad.js";
import { l as normalizeStringEntries } from "../../string-normalization-BUWquf-_.js";
import { a as fetchWithSsrFGuard } from "../../fetch-guard-BKvfwdRa.js";
import { D as resolveChannelMediaMaxBytes } from "../../media-runtime-CjY6o7UI.js";
import { a as normalizeChannelSlug, i as buildChannelKeyCandidates, l as resolveNestedAllowlistDecision, s as resolveChannelEntryMatchWithFallback } from "../../channel-config-BBLiKj96.js";
import { r as resolveDefaultGroupPolicy } from "../../runtime-group-policy-DEj6LNUz.js";
import { n as DEFAULT_WEBHOOK_MAX_BODY_BYTES } from "../../http-body-CbF0Hltn.js";
import { t as PAIRING_APPROVED_MESSAGE } from "../../pairing-message-CFjlYpMw.js";
import { d as createDefaultChannelRuntimeState, i as buildProbeChannelStatusSummary } from "../../status-helpers-DfSmHgNC.js";
import { o as keepHttpServerTaskAlive } from "../../channel-lifecycle.core-BvcgdZUx.js";
import { l as loadOutboundMediaFromUrl } from "../../outbound-media-DGjHHo1-.js";
import { i as logTypingFailure } from "../../logging-yk8JlYZb.js";
import { f as mergeAllowlist, m as summarizeMapping } from "../../allow-from-DAzkuAuT.js";
import { u as dispatchReplyFromConfigWithSettledDispatcher } from "../../inbound-reply-dispatch-BFUnyu8J.js";
import { u as withFileLock } from "../../file-lock-JSDrNuSX.js";
import { r as createChannelPairingController } from "../../channel-pairing-Dd94ZNLz.js";
import { t as chunkTextForOutbound } from "../../text-chunking-CuFAtrpW.js";
import { t as setMSTeamsRuntime } from "../../runtime-api-CniFZODc.js";
export { type AllowlistMatch, type BaseProbeResult, type ChannelDirectoryEntry, type ChannelGroupContext, type ChannelMessageActionName, type ChannelOutboundAdapter, type ChannelPlugin, DEFAULT_ACCOUNT_ID, DEFAULT_WEBHOOK_MAX_BODY_BYTES, type GroupPolicy, type GroupToolPolicyConfig, type MSTeamsChannelConfig, type MSTeamsCloudName, type MSTeamsConfig, type MSTeamsReplyStyle, type MSTeamsTeamConfig, type MarkdownTableMode, type OpenClawConfig, PAIRING_APPROVED_MESSAGE, type PluginRuntime, type ReplyPayload, type RuntimeEnv, type SsrFPolicy, buildChannelKeyCandidates, buildMediaPayload, buildProbeChannelStatusSummary, chunkTextForOutbound, createChannelReplyPipeline as createChannelMessageReplyPipeline, createChannelPairingController, createDefaultChannelRuntimeState, detectMime, dispatchReplyFromConfigWithSettledDispatcher, extensionForMime, extractOriginalFilename, fetchWithSsrFGuard, getFileExtension, isDangerousNameMatchingEnabled, keepHttpServerTaskAlive, loadOutboundMediaFromUrl, logTypingFailure, mergeAllowlist, normalizeChannelSlug, normalizeStringEntries, resolveAllowlistMatchSimple, resolveChannelEntryMatchWithFallback, resolveChannelMediaMaxBytes, resolveDefaultGroupPolicy, resolveNestedAllowlistDecision, resolveToolsBySender, setMSTeamsRuntime, summarizeMapping, withFileLock };