import { n as normalizeAccountId, t as DEFAULT_ACCOUNT_ID } from "../../account-id-Df9e41E6.js";
import { r as buildChannelConfigSchema } from "../../config-schema-BtYVhZQA.js";
import { t as getChatChannelMeta } from "../../chat-meta-D7AWQURI.js";
import { n as AcpRuntimeError } from "../../errors-B_W4aC5J.js";
import { _ as readReactionParams, b as readStringParam, h as readNumberParam, l as jsonResult, v as readStringArrayParam, y as readStringOrNumberParam } from "../../common-BRcU2Dje.js";
import { r as resolvePollMaxSelections } from "../../polls-C-v11_tu.js";
import { t as clearAccountEntryFields } from "../../config-helpers-DU5uyx8S.js";
import { n as formatPairingApproveHint } from "../../helpers-BLGguEiN.js";
import { r as makeProxyFetch } from "../../proxy-fetch-pQvcG8AH.js";
import { i as shouldRetryTelegramTransportFallback, n as resolveTelegramFetch, r as resolveTelegramTransport } from "../../fetch-C8nc2tbM.js";
import { n as collectTelegramUnmentionedGroupIds, t as auditTelegramGroupMembership } from "../../audit-jI-q9VXY.js";
import { r as emptyPluginConfigSchema } from "../../config-schema-DFg2Z2_b.js";
import "../../channel-core-OtsQuafx.js";
import { t as resolveTelegramToken } from "../../token-BJWjAHe2.js";
import { a as resolveConfiguredFromCredentialStatuses, r as projectCredentialSnapshotFields } from "../../account-snapshot-fields-VbzFdu8Y.js";
import "../../acp-runtime-BwPaZGW6.js";
import { t as PAIRING_APPROVED_MESSAGE } from "../../pairing-message-DNhqI-OE.js";
import "../../channel-plugin-common-DZlkjCGs.js";
import { o as buildTokenChannelStatusSummary } from "../../status-helpers-BevxX6Pu.js";
import "../../channel-status-DxlXr0Xh.js";
import { c as TelegramConfigSchema } from "../../bundled-channel-config-schema-DdNaBuhs.js";
import "../../channel-actions-TpPb-Ab3.js";
import { r as setTelegramRuntime } from "../../runtime-B_f_VNpK.js";
import { a as buildTelegramExecApprovalPendingPayload, o as shouldSuppressTelegramExecApprovalForwardingFallback, r as monitorTelegramProvider, s as telegramMessageActions, t as probeTelegram } from "../../probe-CeDnKd1l.js";
import { t as parseTelegramTopicConversation } from "../../topic-conversation-B6kdtLDb.js";
import "../../config-api-B6VKBitS.js";
import { c as setTelegramThreadBindingMaxAgeBySessionKey, i as getTelegramThreadBindingManager, o as resetTelegramThreadBindingsForTests, r as createTelegramThreadBindingManager, s as setTelegramThreadBindingIdleTimeoutBySessionKey } from "../../thread-bindings-BfZBw0s3.js";
import { r as resolveTelegramRuntimeGroupPolicy } from "../../group-access-CTmGfXFI.js";
import { a as editMessageTelegram, c as renameForumTopicTelegram, d as sendPollTelegram, f as sendStickerTelegram, i as editMessageReplyMarkupTelegram, m as unpinMessageTelegram, n as deleteMessageTelegram, o as pinMessageTelegram, p as sendTypingTelegram, r as editForumTopicTelegram, s as reactMessageTelegram, t as createForumTopicTelegram, u as sendMessageTelegram } from "../../send-DcY8C3CL.js";
import { t as resolveTelegramPollVisibility } from "../../poll-visibility-Ds4ydsWS.js";
export { AcpRuntimeError, DEFAULT_ACCOUNT_ID, PAIRING_APPROVED_MESSAGE, TelegramConfigSchema, auditTelegramGroupMembership, buildChannelConfigSchema, buildTelegramExecApprovalPendingPayload, buildTokenChannelStatusSummary, clearAccountEntryFields, collectTelegramUnmentionedGroupIds, createForumTopicTelegram, createTelegramThreadBindingManager, deleteMessageTelegram, editForumTopicTelegram, editMessageReplyMarkupTelegram, editMessageTelegram, emptyPluginConfigSchema, formatPairingApproveHint, getChatChannelMeta, getTelegramThreadBindingManager, jsonResult, makeProxyFetch, monitorTelegramProvider, normalizeAccountId, parseTelegramTopicConversation, pinMessageTelegram, probeTelegram, projectCredentialSnapshotFields, reactMessageTelegram, readNumberParam, readReactionParams, readStringArrayParam, readStringOrNumberParam, readStringParam, renameForumTopicTelegram, resetTelegramThreadBindingsForTests, resolveConfiguredFromCredentialStatuses, resolvePollMaxSelections, resolveTelegramFetch, resolveTelegramPollVisibility, resolveTelegramRuntimeGroupPolicy, resolveTelegramToken, resolveTelegramTransport, sendMessageTelegram, sendPollTelegram, sendStickerTelegram, sendTypingTelegram, setTelegramRuntime, setTelegramThreadBindingIdleTimeoutBySessionKey, setTelegramThreadBindingMaxAgeBySessionKey, shouldRetryTelegramTransportFallback, shouldSuppressTelegramExecApprovalForwardingFallback, telegramMessageActions, unpinMessageTelegram };
